stages:
  train:
    cmd: python src/model.py
    deps:
      - src/model.py
      - params.yaml
      - train/train.csv
    outs:
      # Heavy weights and data arrays are securely managed by DVC
      - best_traditional_model.pkl
      - ann_classifier_model.h5
      - scaler.pkl
      - label_encoder.pkl
      - training_history.pkl
      - X_train_scaled.npy
      - X_test_scaled.npy
      - y_train.npy
      - y_test.npy
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - best_traditional_model.pkl
      - ann_classifier_model.h5
      - X_test_scaled.npy
      - y_test.npy
      - training_history.pkl
      - params.yaml