stages:
  train:
    cmd: python src/model.py
    deps:
      - src/model.py
      - params.yaml
      - train/train.csv
    outs:
      - models/model.keras
      - artifacts/feature_columns.json
      - artifacts/label_encoder_mapping.json
      - artifacts/scaler_params.json
      - artifacts/X_test_scaled.npy
      - artifacts/y_test.npy
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.keras
      - artifacts/X_test_scaled.npy
      - artifacts/y_test.npy
      - params.yaml
    metrics:
      - metrics.json:
          cache: false